title: Flashcard
# name: John Doe
# user_description: Programmer (Interested in Philosophy and Math)
# notes_url: ""
# profile_pic: /assets/img/profile.png
# favicon: /assets/img/favicon.png
copyright_name: yeungn
baseurl: "/flashcard" # the subpath of your site, e.g. /blog
url: "https://yeungndev.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
encoding: utf-8

# Build settings
theme: null
plugins:
  - jekyll-feed 
  - jekyll-sitemap 

markdown: kramdown

kramdown:
  input: GFM
  hard_wrap: false
  math_engine: mathjax
  smart_quotes: ["apos", "apos", "quot", "quot"]
  syntax_highlighter: rouge

sass:
  style: compressed

collections:
    notes:
      output: true
      permalink: /notes/:title

# disqus:
#   shortname: raghuveerdotnet

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      permalink: /posts/:title
      content-type: post
  - scope:
      path: ""
      type: notes
    values:
      layout: notes
      content-type: notes
